---
# tasks file for lighthouse-role
- name: Install LightHouse and publish
  become: true
  block:
    - name: LightHouse | Get from git repo
      ansible.builtin.git:
        repo: "{{ lighthouse_git }}"
        version: master
        dest: "{{ lighthouse_home_dir }}"
    - name: LightHouse | LightHouse nginx config
      become: true
      ansible.builtin.template:
        src: lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: 0644
      notify: Reload Nginx
